### PR TITLE
Operator

### PR DESCRIPTION
**Pull request by FahadBuilds**
This PR has the code for the operator. 

- There are CLI and GUI operators
- The operators talk to the server on a separate socket that is specified when the server is ran
- The server can serve an arbitrary amount of operators
- In GUI, an operator can interact with multiple sessions simultaneously 

Misc:
- Server has been restructured to be class-based, made headless
- Reorganized project file structure so that client and server can both import from common files
    - Renamed `implant` directory to `avocado` to avoid conflicts with the generated `implant` file

### CODE REVIEW

**Comment by custards** [comment]
Looks solid!

**Comment by TopShelfAsian** [comment]
Looks good to me!

**Comment by sadeli413** [comment]
1. Bug, `id` is not declared: https://github.com/ProDefense/Avocado/blob/dev-op/src/client/gui/active_session_logic.py#L34
2. Bad type hint: https://github.com/ProDefense/Avocado/blob/dev-op/src/server/mtls/mtls.py#L45 (use import typing.Tuple)
3. Bad type hint: https://github.com/ProDefense/Avocado/blob/dev-op/src/server/handler/handler.py#L7 (use import typing.Dict but this isn't even a dictionary, it's a list: https://github.com/ProDefense/Avocado/blob/dev-op/src/avocado-server#L39)
4.

**Comment by sadeli413** [comment]
4. Operator connects to the server with plaintext TCP. Use mTLS instead https://github.com/ProDefense/Avocado/blob/dev-op/src/client/listener/listener.py#L11. 
5. This is called listener, but the client never listens on any port anything. Rename to something like "mtls_client" or "rpc_client" https://github.com/ProDefense/Avocado/tree/dev-op/src/client/listener.
6.

**Comment by sadeli413** [comment]
6. Just an opinion, but logical communication with the operator should either be in `handler.py` or a new file called `operator_handler.py`. If you add a new file called `operator_handler.py` then rename the existing `handler.py` to `implant_handler.py` https://github.com/ProDefense/Avocado/blob/dev-op/src/avocado-server#L67

**Comment by FahadSec** [comment]
@sadeli413 Thanks for the feedback. Just resolved all except (4), because it's an active issue. (https://github.com/ProDefense/Avocado/issues/24).

**Pull request merged**
